apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
namespace: rollouts-demo-dev
configMapGenerator:
  - name: rollouts-demo-config
    behavior: merge
    literals:
      - ENV_NAME=dev
