apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: rollouts-demo
  name: rollouts-demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: rollouts-demo
  type: ClusterIP
